addSbtPlugin("org.scalastyle"        %% "scalastyle-sbt-plugin" % "0.8.0")
addSbtPlugin("org.brianmckenna"      % "sbt-wartremover"        % "0.14")
addSbtPlugin("org.scoverage"         % "sbt-scoverage"          % "1.3.3")
addSbtPlugin("com.typesafe.play"     % "sbt-plugin"             % "2.4.4")
addSbtPlugin("com.typesafe.sbt"      % "sbt-multi-jvm"          % "0.3.11")
addSbtPlugin("de.heikoseeberger"     % "sbt-header"             % "1.5.0")

//addSbtPlugin("com.scalapenos"        % "sbt-prompt"             % "0.2.1")
//addSbtPlugin("com.typesafe.sbt"      % "sbt-git"                % "0.8.5")
//addSbtPlugin("com.github.gseitz"     % "sbt-release"            % "0.8.5")
//addSbtPlugin("com.eed3si9n"          % "sbt-buildinfo"          % "0.5.0")
